#!/usr/bin/env bash
set +o posix

################################ LIBRARIES SHARED OVER ALL CW SCRIPTS ################################

  #
  ## Exit code of the script
  ## 0 - success
  ## 1 - un-success (bad options/... etc)
  ## 2 - unexpected error (wrong code)
  #
declare ret=0

args=()

################################ STANDARD BOOTSTRAP CALL ################################
umbrella_bootstrap


################################ BRANCH-SPECIFIC HELP ################################
function show_help() {
cat << EOF

NAME:
    ${FLAGS_PREFIX} commit current lego

SYNOPSIS:
    '${FLAGS_PREFIX} [<any-git-commit-options>] [-v|--verbose] [<path-resolution>] -- [[<module-name>] ...]'

DESCRIPTION:


EXAMPLES:
    '${FLAGS_PREFIX} -v .' -> show verbose status for current module only


OPTIONS:
      --help|-h|-\?
          get this help

      --
          marks state after which repositories will be shown in status.


EOF
}

#echo  "${cwRoot} ${gitDir}"
typeset verbose=0
typeset afterDash=()
typeset stopOptions=0
typeset initialPath commitMessage commitTemplate doRecursive=0 reuse doAppendUntracked=1
#set -x

################################ PARAMETERS PARSING ################################
while [[ -n $1 ]]; do
  noAppendArg=0
  case $1 in
    -h|-\?|--help)
      show_help
      exit
      ;;
    -v|--verbose)
      verbose=$((verbose + 1)) # Each -v argument adds 1 to verbosity.
      ;;

    --)
      stopOptions=1
      ;;

    --recursive|-r)
      doRecursive=1
      ;;
    --no-recursive|-R)
      doRecursive=0
      ;;

    -[amFtscC]*)
      args+=($1)
      #getopts emulation -am...
      lastOption=${1:(-1)}
      if [[ $lastOption == "m" ]]; then
        args+=("\"$2"\")
        commitMessage=$2
        shift
      elif [[ $lastOption == "t" ]]; then
        args+=("\"$2"\")
        commitTemplate=$2
        shift
      elif [[ $lastOption == "c" || $lastOption == "C"  || $lastOption == "F" ]]; then
        args+=("\"$2"\")
#        reuse=$2
        shift
#      else
        # TODO ?? change behaviour for -a|--add option
        # in umbrella it will add untracked files as well
      fi
      ;;

    --append-untracked|-u)
      doAppendUntracked=1
      ;;
    --no-append-untracked|-U)
      doAppendUntracked=0
      ;;

    --message)
      args+=($1)
      args+=("\"$2\"")
      commitMessage=$2
      shift
      ;;
    --message=*)
      commitMessage=${1#*=}
      [[ -z ${commitMessage} ]] && die "message is not given $1"
      args+=("\"$1\"")
      ;;

    --template)
      args+=($1)
      commitTemplate=$2
      shift
      ;;
    --template=*)
      commitTemplate=${1#*=}
      [ -z ${commitTemplate} ] && die "template is not given $1"
      args+=($1)
      ;;
    *)
      if (( $stopOptions )); then
        if [[ -z ${1%%-*} ]]; then
          die "after '--' additional options ($1) are not allowed "
        else
          afterDash+=($1)
        fi
      elif [[ -z ${1%%-*} ]]; then
        args+=($1)
      elif [[ -z ${initialPath} ]]; then
        initialPath=$1
      else
        die "error in parameters [$1]"
      fi
      ;;
  esac
  shift
done


################################ SCRIPT SPECIFIC METHODS ################################
function prepare_commit_level() {
  local levelPath="$1"
  [[ -z ${levelPath} ]] && panic "$FUNCNAME()... parameter 'path' is required"
  local moduleName="$2"
  local repoBranch
  local ret=0   # return code, 0 - the repo is syncronized
  local childRet # child return code
  local modulePath=$3

  ## TODO changed params order
  module_porcelain_status "${modulePath}" commit

  local applied=1
  if (( ${MODULE_STATUS[$MS_COMMITABLE]} )); then
    drop_to_affected ${levelPath}
    applied=$?

    if (( ! $applied )); then
      affected=1
      [[ -z ${commitMessage} ]] && onEmptyMessage+="${moduleName}, "
    fi
  fi

  if (( $applied )); then
    skippedModules+=(${moduleName})
  fi

  if [ -f .gitmodules ]; then
    while read -a module; do
      childRet=0
      subModule="${module[0]}"
      localPath="${module[1]}"
      subRepoPath="${levelPath}"/"${localPath}"

      pushd "${subRepoPath}" &>/dev/null
      local subModulePath="$3" #/$subModule"
      if [[ ${subModulePath:(-1)} != "/" ]]; then
        subModulePath+="/"
      fi
      subModulePath+="$subModule"
#      stopMachine=$(( $stopMachine + 1 ))
#      (( $stopMachine > 2 )) && exit 3
      prepare_commit_level "${subRepoPath}" "${subModule}" "${subModulePath}"
      childRet=$?
      (( $childRet > $ret )) && ret = ${childRet}
      popd  &>/dev/null
    done < <(git config -f .gitmodules --get-regexp "submodule.*.path" | sed -E "s/submodule\.(.*)\.path/\1/")
  fi
}

################################ MAIN SCRIPT LOGIC ################################
cmd_default() {
  typeset modulePath=$(resolve_module_path "${initialPath}" ".")

set -x
  read moduleName moduleFilePath initialized managed < <(module_info "${modulePath}" "name" "path" "initialized" "managed")
set +x

  typeset affected=0
  typeset onEmptyMessage
  typeset skippedModules=()
  [[ -z ${commitMessage} ]] && onEmptyMessage="commit for ${globals[$G_ROOT_NAME]}, affected modules: "

  if (( $initialized )) && (( $managed )); then

    pushd ${moduleFilePath} &>/dev/null
    prepare_commit_level "${moduleFilePath}" "${moduleName}" "${modulePath}"

    if (( $affected )); then
      if [[ -z ${commitMessage} && -n ${onEmptyMessage} ]]; then
       args+=('--message' )
       args+=(" \"${onEmptyMessage:0:(${#onEmptyMessage}-2)})\"")
      fi

    #cat ${globals[$G_AFFECTED_MODULES]}

      while read -a module; do
        cd ${module[$MFS_FULL_PATH]}
        level_verbose_about_to ${module[@]}
    #    echo "git commit ${args[@]} ${#args[@]}"

        (( $doAppendUntracked )) && git add . -A
echo "${args[@]}" >&2
        git commit "${args[@]}"
      done < <(cat ${globals[$G_AFFECTED_MODULES]} | (tac 2> /dev/null || tail -r))
    fi
  fi

  if (( ${#skippedModules} )); then
    cw_echo "Not affected modules: ${skippedModules[*]}"
  fi

  popd &>/dev/null
  umbrella_finalize

#  exit $ret
}