#!/usr/bin/env bash
set +o posix

################################ LIBRARIES SHARED OVER ALL CW SCRIPTS ################################

  #
  ## Exit code of the script
  ## 0 - success
  ## 1 - un-success (bad options/... etc)
  ## 2 - unexpected error (wrong code)
  #
declare ret=0

args=()

################################ STANDARD BOOTSTRAP CALL ################################
umbrella_bootstrap


################################ BRANCH-SPECIFIC HELP ################################
function show_help() {
cat << EOF

NAME:
    ${FLAGS_PREFIX} stash in git umbrella-managed modules

SYNOPSIS:
    '${FLAGS_PREFIX} [<any-git-stash-options>] [-v|--verbose] [<path-resolution>] -- [[<module-name>] ...]'

DESCRIPTION:


EXAMPLES:
    '${FLAGS_PREFIX} -v .' -> show verbose status for current module only


OPTIONS:
      --help|-h|-\?
          get this help

      --
          marks state after which repositories will be shown in status.


EOF
}

typeset verbose=0
typeset afterDash=()
typeset stopOptions=0
typeset doRecursive=0 reuse

typeset initialPath
typeset modulePath
typeset moduleName
typeset moduleFilePath
typeset moduleInitialized
typeset moduleGitDir
#set -x

################################ PARAMETERS PARSING ################################
while [[ -n $1 ]]; do
  noAppendArg=0
  case $1 in
    -h|-\?|--help)
      show_help
      exit
      ;;
    -v|--verbose)
      verbose=$((verbose + 1)) # Each -v argument adds 1 to verbosity.
      ;;

    --)
      stopOptions=1
      ;;

    --recursive|-r)
      doRecursive=1
      ;;
    --no-recursive|-R)
      doRecursive=0
      ;;

    *)
      if (( $stopOptions )); then
        if [[ -z ${1%%-*} ]]; then
          die "after '--' additional options ($1) are not allowed "
        else
          afterDash+=($1)
        fi
      elif [[ -z ${1%%-*} ]]; then
        args+=($1)
      elif [[ -z ${initialPath} ]]; then
        initialPath=$1
      else
        die "error in parameters [$1]"
      fi
      ;;
  esac
  shift
done


################################ SCRIPT SPECIFIC METHODS ################################
function prepare_stash_level () {
  local modulePath="$1"
  local moduleName="$2"
  local levelPath="$3"

  pushd "$levelPath" &>/dev/null

  drop_to_affected "$levelPath"

#git cat-file -p 5458 | grep -Eo "^author.* [[:digit:]]{10} [+-][[:digit:]]{4}" | sed -E "s/^author.* ([[:digit:]]{10}) [+-][[:digit:]]{4}/\1/"

  # do recurse call for every sub-repos
  while read -a module; do
    local subModule="${module[0]}"
    local localPath="${module[1]}"
    local moduleFilePath="$levelPath"/"$localPath"

    local childModulePath="$modulePath"
    if [[ ${modulePath:(-1)} != "/" ]]; then
      local childModulePath+="/"
    fi
    childModulePath+="$subModule"

    prepare_stash_level "$childModulePath" "$subModule" "$moduleFilePath"
  done < <(git config -f .gitmodules --get-regexp "submodule.*.path" | sed -E "s/submodule\.(.*)\.path/\1/")

  popd &>/dev/null

}  ## of stash_level


################################ MAIN SCRIPT LOGIC ################################
#set -x
cmd_default() {
  typeset dieMsg
  typeset skippedModules=()
  typeset affected=0
  typeset vetoed=0
  #pushd ${path} &>/dev/null
  cd "$moduleFilePath"

  prepare_stash_level "$modulePath" "$moduleName" "$moduleFilePath"

  if (( $affected )); then

    while read -a module; do
#      cd ${module[$MFS_FULL_PATH]}

      git stash "${args[@]}"
    done < <(cat ${globals[$G_AFFECTED_MODULES]} | (tac 2> /dev/null || tail -r))
  fi

  if (( ${#skippedModules} )); then
    cw_echo "Not affected modules: ${skippedModules[*]}"
  fi

#  popd &>/dev/null
  umbrella_finalize

  exit $ret
}