#!/usr/bin/env bash
set +o posix

################################ LIBRARIES SHARED OVER ALL CW SCRIPTS ################################
args=()

################################ STANDARD BOOTSTRAP CALL ################################
#set -x
umbrella_bootstrap
#set +x

cwRoot="${globals[$G_ROOT_DIR]}"
cwTmpSubmodules="${globals[$G_MODULES_FN]}"
gitDir="${globals[$G_MODULE_GIT_DIR]}"


################################ BRANCH-SPECIFIC HELP ################################
function show_help() {
cat << EOF

NAME:
    ${0##*/} tool to manage checkouts different version onto umbrella-managed git repositories

SYNOPSIS:
    ${0##*/} --[no-]current [--[no-]recursive] ...] [[--fallback <branch1> ...] ([--[no-]push] | [--[no-]commit] | <revision|reference-resolution>) [<path-resolution>] -- <module1> ...

DESCRIPTION:
    Checkout in umbrella mode handles slightly differ from its 'git checkout' counterpart.
    First it don\'t works with file or files after -- trigger. In umbrella it will works with
    modules\' list. In absolute convention it defines modules affecting on checkout.

    Umbrella checkout processing falling into three different modes.
    1) solo mode is just revision-resolution direct or inderect reference to specific commit,
        rather than symbolic ref aka branch.
    2) if no solo mode - relative mode, if path-resolution follows to be a path relative to current directory.
    3) if path-resolution directs to the umbrella module, it will be an absolute mode, or setting it to '/'
        or if path-resolution parameter just omitted.

    For solo mode all parameters except umbrella-specific will be used as parameters for usual 'git commit ... '
    command. For two other modes usual git checkout parameters are not permitted.

    CAUTION!
    Umbrella checkout does NOT supports --branch|--orphan functionality. It is moved to
    'branch <branch-name>' to avoid over-complicated scenarios can happening in multi-repo architecture.


EXAMPLES:
    '${0##*/} master /' -> absolute mode, --no-recursive, --current, --no-commit, --no-push
        ACTION: if umbrella module branch is different from master, it will be checked out to master,
        all sub-modules will be updated to master as well

    '${0##*/} master' -> same as above

    '${0##*/} develop .' -> relative mode, --no-recursive, --current, --commit, --push
        This action may cause (or may not) enclosed module to be dirty, if previous commit differs to develop.
        ACTION: if umbrella module branch differs from develop, it will be checked out to develop,
        all sub-modules have to be updated to develop as well. If there is any module having no develop branch,
        getting warning about this, no commit (if no --force given), state of that module is not changed.

    '${0##*/} --fallback=develop qa' -> absolute mode, --recursive, --current, --commit, --push
        ACTION: if umbrella module branch differs from develop, it will be checked out to develop,
        all sub-modules have to be updated to develop as well. Any of module has no develop branch,
        but has develop, will be checked out to develop.

    '${0##*/} --fallback=develop --fallback=master qa' -> same as above, but if no qa and develop exists,
        change to master

    '${0##*/} master .' -> relative mode, --no-recursive, --current, --no-commit, --no-push
        Change for current module to master branch. Get warning, if enclosing repo not referencing to master.
        All options except umbrella-specific will be passed to underlying 'git checkout ...' command.

    '${0##*/} release . --commit --push' -> solo mode, --no-recursive, --current, --push
        all predecessor modules will be updated to new state, if required. After they will be committed and
        pushed to origin.

    '${0##*/} release ./wiki' -> relative mode, change branch for first sibling wiki module to 'release', --commit

    '${0##*/} release -- wiki docs' -> absolute, looking from umbrella root, doesn\'t matter deep of module.


OPTIONS:
      --help|-h|-\?
          get this help

      --[no-]push[=<remote>]
          push (or prevent) to <remote> ('origin' by default) repository.

      --[no]-commit]
          valid with --view option only. Attempts to fix the branding modules hierarchy
          if possible. By default --sync is not performed

      --fallback[=| ]<branch>
          fallback branch name used instead of <fork-branch>, if last does not exists in sub-module

      --
          marks state after which only affected repositories will be enumerated. Actual with --[no-]current
          options only.

          ...

          to be continued

EOF
}

typeset verbose=0
typeset doAdd=0 # by default do not add
typeset revision
typeset commit=1 force=0
typeset fallbacks=()
typeset initialPath 

################################ PARAMETERS PARSING ################################
while [[ -n $1 ]]; do
  (( $stopOptions )) && [[ -z ${1%%-*}  ]] && die "after '--' additional options ($1) are not allowed "
  noAppendArg=0
  case $1 in
    -h|-\?|--help)
      show_help
      exit
      ;;
    -v|--verbose)
      verbose=$((verbose + 1)) # Each -v argument adds 1 to verbosity.
      noAppendArg=1
      ;;

    --fallback)
      if [ -n "$2" ]; then
        noAppendArg=1
        ${fallbacks[${#fallbacks[@]}]}=$2
        shift
      else
        die "--fallback requires a non-empty option argument."
      fi
      ;;
    --fallback=?*)
      noAppendArg=1
      ${fallbacks[${#fallbacks[@]}]}=${1#*=} # Delete everything up to "=" and assign the remainder.
      ;;
    --fallback=)         # Handle the case of an empty --fallback=
      die "--fallback requires a non-empty option argument."
      ;;


    --commit)
      commit=1
      ;;
    --no-commit)
      commit=0
      ;;

    --force|-f)
      force=1
      ;;
    --no-force|-F)
      force=0
      ;;

    -b|-B|--orphan)
      die "$1 options is not supported for now. Create new branches using CW 'branch ...' command" >&2
      ;;
    *)
      if [[ -z ${1%%-*} ]]; then
        die "Unknown option '$1'"
      elif [[ -z ${revision} ]]; then
        revision=$1
        noAppendArg=1
      elif [[ -z ${initialPath} ]]; then
        initialPath=$1
      fi
      ;;
  esac
  (( ${noAppendArg} )) && args+=$1
  shift
done


if [[ -z $revision ]]; then
  die "Parameter revision/branch required"
fi
#set -x

################################ SCRIPT SPECIFIC METHODS ################################
checkout_level () {
  local levelRevision="$1"
  local modulePath="$2"
  local moduleName="$3"
  local levelPath="$4"
  local doUpdate="$5"
  local parentCheckBranch="$6"

  local parentCheckCommit="$7"
  local parentRevision="${parentCheckBranch}"
  if [[ -z "${parentRevision}" ]]; then
    parentRevision="${parentCheckCommit}"
  fi

  if [[ -n "${parentRevision}" ]]; then
    levelRevision="${parentRevision}"
  fi

  if [[ -z "${levelRevision}" ]]; then
    panic "$FUNCNAME: Empty revision"
  fi

  local -a modulesBefore
  local -a modulesAfter
  local -a removedModules
  local -a addedModules

  pushd "${levelPath}" &> /dev/null

#  cd "${levelPath}"
#  echo "---> checkout_level ${levelPath}"

  while read -a module; do
    modulesBefore+=("${module[0]}")
  done < <(git config --file .gitmodules --get-regexp "submodule.*.path" | sed -E "s/submodule\.(.*)\.path/\1/")

  pwd
  git checkout ${levelRevision}
#  echo $?

  while read -a module; do
    modulesAfter+=("${module[0]}")
  done < <(git config --file .gitmodules --get-regexp "submodule.*.path" | sed -E "s/submodule\.(.*)\.path/\1/")

  for b in ${modulesBefore[@]}; do
    local found=0
    for a in ${modulesAfter[@]}; do
      if [[ $a == $b ]]; then
        found=1
        break
      fi
    done
    if (( ! $found )); then
      removedModules[${#removedModules[@]}]="${b}"
    fi
  done

  for a in ${modulesAfter[@]}; do
    found=0
    for b in ${modulesBefore[@]}; do
      if [[ $a == $b ]]; then
        found=1
        break
      fi
    done
    if (( ! $found )); then
      addedModules[${#addedModules[@]}]="$a"
    fi
  done

  (( "${#addedModules[@]}" )) && git submodule update --init

  #By change branch can happen that submodules can't be removed (usually can) if, for example, if submodule has its own submodule.
  (( "${#removedModules[@]}" )) && git clean -d -f -f &> /dev/null

  # do recurse call for every sub-repos
  while read -a module; do
    local subModule="${module[0]}"
    local localPath="${module[1]}"
    local path="${levelPath}"/"${localPath}"

#      checkoutd "${path}" &> /dev/null
    local childModulePath="${modulePath}"
    if [[ ${modulePath:(-1)} != "/" ]]; then
      local childModulePath+="/"
    fi
    childModulePath+="$subModule"

    local deleted=0
    for d in ${removedModules[@]}; do
      if [[ ${d} == ${subModule} ]]; then
        deleted=1
        break
      fi
    done

#    local added=0
#    for a in ${addedModules[@]}; do
#      if [[ ${a} == ${subModule} ]]; then
#        added=1
#        break
#      fi
#    done

    if (( ! $deleted )); then
      local branchAfter=$(git config --file .gitmodules --get "submodule.${subModule}.branch")
      local commitAfter=$(git config --file .gitmodules --get "submodule.${subModule}.commit")

      checkout_level "-" "${childModulePath}" "${subModule}" "${path}" "${added}" "${branchAfter}" "${commitAfter}"
    fi
  done < <(git config -f .gitmodules --get-regexp "submodule.*.path" | sed -E "s/submodule\.(.*)\.path/\1/")

  popd &> /dev/null
}  ## of checkout_level



################################ MAIN SCRIPT LOGIC ################################
cmd_default() {
  typeset modulePath=$(resolve_module_path "${initialPath}" "/")
  read moduleName path < <(module_info "${modulePath}" "name" "path")
  typeset dieMsg
  typeset skippedModules=()
  typeset affected=0
  typeset vetoed=0

  #pushd ${path} &>/dev/null
  cd ${path}
  git rev-parse "${revision}" &> /dev/null
  if (( $? )); then
    git rev-parse "origin/${revision}" &> /dev/null
    if (( $? )); then
      die "Revision '$revision' not exists in the module '$moduleName'"
    fi
  fi

  prepare_checkout_level "${revision}" "${modulePath}" "${moduleName}" "${path}" 0
  if (( $? )); then
    if [[ -n $dieMsg ]]; then
      die "${dieMsg}"
    fi
  fi

  #set -x
  checkout_level "${revision}" "${modulePath}" "${moduleName}" "${path}" 0
  #popd &> /dev/null can be meanwhile already removed

  exit 0
}